# ChipForAll Makefile
# Philosophy: Keep it simple. Delegate logic to c4o-core.

# Image Configuration
#
# Pinned to the minor, not the patch. c4o-core publishes 2.18.0, 2.18, 2 and
# latest for every release; 2.18 means a fix reaches you without anybody editing
# this line -- for as long as 2.18 is c4o-core's newest minor. Only the newest
# minor gets fixes, so once 2.19 is out this line has to move to keep getting
# them. A new behaviour never arrives unannounced. Pin 2.18.0 instead if you
# want a byte-identical image forever, and remember that you then also own
# noticing its fixes.
#
# Two files carry this version -- here and .devcontainer/devcontainer.json. CI
# refuses to continue when they disagree, so change both together. The workflow
# reads the image name from this line.
C4O_IMAGE := ghcr.io/anlit75/c4o-core:2.18
LIBRELANE_IMAGE := ghcr.io/librelane/librelane:3.0.14

# --- From here down this file is c4o-core's stub.mk. Do not edit it. ---
#
# The commands -- make all, make gds, make report and the rest -- are in the
# c4o-core image named above, in /opt/c4o-core/rules.mk, so a fix to them
# arrives with the image. `make help` lists them. Targets of your own go below
# the include; docs/makefile.md in c4o-core says what they may use.
#
# Inside the image (the Dev Container) the rules are a local file. On a host
# they are copied out of the image into .c4o/, once for each image: the file is
# named after the image's id, so the rules are always the ones of the image
# that runs, and a `docker pull` that brings a newer image brings its rules.
#
# C4O_RULES=<file> uses that file and no Docker at all.
ifndef C4O_RULES
ifneq ($(wildcard /opt/c4o-core/rules.mk),)
C4O_RULES := /opt/c4o-core/rules.mk
else
C4O_IMAGE_ID := $(shell docker image inspect -f '{{.Id}}' $(C4O_IMAGE) 2>/dev/null)
ifeq ($(C4O_IMAGE_ID),)
$(info Pulling $(C4O_IMAGE) ...)
C4O_IMAGE_ID := $(shell docker pull -q $(C4O_IMAGE) >/dev/null 2>&1; docker image inspect -f '{{.Id}}' $(C4O_IMAGE) 2>/dev/null)
endif
ifeq ($(C4O_IMAGE_ID),)
$(error Cannot get $(C4O_IMAGE). The commands of this Makefile come out of that image, so it needs Docker running and the image name to be right. Check 'docker info' and 'docker pull $(C4O_IMAGE)')
endif
C4O_RULES := .c4o/$(subst sha256:,,$(C4O_IMAGE_ID)).mk
$(C4O_RULES):
	@mkdir -p .c4o
	@rm -f .c4o/*.mk .c4o/*.tmp
	@docker run --rm --entrypoint cat $(C4O_IMAGE) /opt/c4o-core/rules.mk > $@.tmp \
		|| { rm -f $@.tmp; echo "❌ [ERROR] $(C4O_IMAGE) has no /opt/c4o-core/rules.mk. This Makefile needs c4o-core 2.17 or newer."; exit 1; }
	@mv $@.tmp $@
endif
endif
include $(C4O_RULES)

.PHONY: rtl ral

help::
	@echo "  make rtl     - Regenerate src/apb_uart_sv.v from the vendored SystemVerilog"
	@echo "  make ral     - Regenerate test/uart_ral.py from regs/apb_uart.rdl"

# --- The DUT is generated, and the generated file is committed ---

# src/vendor/apb_uart_sv/ is somebody else's SystemVerilog. Nothing in this
# image reads it: yosys 0.33 stops at apb_uart_sv.sv:42 with "syntax error,
# unexpected '['". sv2v translates it to the Verilog-2005 that yosys, Icarus
# and LibreLane all accept.
#
# The result is committed rather than built on demand, because VERILOG_FILES is
# validated as a literal path -- LibreLane would refuse a file that does not
# exist yet, so `make gds` on a fresh clone has to find it already there. CI
# re-runs this target and fails if the committed file differs, which is what
# stops it drifting from the SystemVerilog above it.
#
# File order is src_files.yml's, and sv2v's output is deterministic, so
# re-running this on an unchanged source is a no-op.
VENDOR_SV := \
	src/vendor/apb_uart_sv/apb_uart_sv.sv \
	src/vendor/apb_uart_sv/uart_rx.sv \
	src/vendor/apb_uart_sv/uart_tx.sv \
	src/vendor/apb_uart_sv/io_generic_fifo.sv \
	src/vendor/apb_uart_sv/uart_interrupt.sv

rtl:
	@echo "🟢 sv2v: $(words $(VENDOR_SV)) SystemVerilog files -> src/apb_uart_sv.v"
	@{ \
		echo "// GENERATED by \`make rtl\` from src/vendor/apb_uart_sv/*.sv -- do not edit."; \
		echo "//"; \
		echo "// sv2v turns the vendored SystemVerilog into the Verilog-2005 that yosys and"; \
		echo "// Icarus read. Without it, yosys 0.33 stops at apb_uart_sv.sv:42 with"; \
		echo "// \"syntax error, unexpected '['\". Committed rather than built on demand so"; \
		echo "// that a fresh clone can run the flow, and checked in CI so it cannot drift"; \
		echo "// from the SystemVerilog above it."; \
		echo "//"; \
		echo "// The Solderpad 0.51 terms in src/vendor/apb_uart_sv/LICENSE cover this file"; \
		echo "// too: it is the same design, mechanically translated."; \
		echo "//"; \
		echo "// The \`timescale is ours, not sv2v's, and not decoration. Without it Icarus"; \
		echo "// runs this file at a precision of one second, while the PDK cell models a"; \
		echo "// gate-level run compiles alongside it carry 1ns/1ps -- so \`make cocotb\` and"; \
		echo "// \`make cocotb-gl\` saw two different meanings of time, and the same clock"; \
		echo "// period meant 10 ns on the gates and 10 s on the RTL."; \
		echo ""; \
		echo "\`timescale 1ns / 1ps"; \
		echo ""; \
		$(call c4o_tool,sv2v) $(VENDOR_SV); \
	} > src/apb_uart_sv.v

# regs/apb_uart.rdl is the register map, and test/uart_ral.py is what PeakRDL
# makes of it. Committed for the same reason src/apb_uart_sv.v is: a fresh clone
# has to be able to run the tests, and CI regenerates and diffs so the two cannot
# drift.
#
# The output is left exactly as peakrdl writes it -- no header of ours -- so that
# the diff in CI is against the tool's output and nothing else. What the map says
# and what it cannot say is written in the .rdl.
ral:
	@echo "🟢 peakrdl pyuvm: regs/apb_uart.rdl -> test/uart_ral.py"
	$(call c4o_tool,peakrdl) pyuvm regs/apb_uart.rdl -o test/uart_ral.py
