// GENERATED by `make rtl` from src/vendor/apb_uart_sv/*.sv -- do not edit.
//
// sv2v turns the vendored SystemVerilog into the Verilog-2005 that yosys and
// Icarus read. Without it, yosys 0.33 stops at apb_uart_sv.sv:42 with
// "syntax error, unexpected '['". Committed rather than built on demand so
// that a fresh clone can run the flow, and checked in CI so it cannot drift
// from the SystemVerilog above it.
//
// The Solderpad 0.51 terms in src/vendor/apb_uart_sv/LICENSE cover this file
// too: it is the same design, mechanically translated.
//
// The `timescale is ours, not sv2v's, and not decoration. Without it Icarus
// runs this file at a precision of one second, while the PDK cell models a
// gate-level run compiles alongside it carry 1ns/1ps -- so `make cocotb` and
// `make gatesim` saw two different meanings of time, and the same clock
// period meant 10 ns on the gates and 10 s on the RTL.

`timescale 1ns / 1ps

module apb_uart_sv (
	CLK,
	RSTN,
	PADDR,
	PWDATA,
	PWRITE,
	PSEL,
	PENABLE,
	PRDATA,
	PREADY,
	PSLVERR,
	rx_i,
	tx_o,
	event_o
);
	reg _sv2v_0;
	parameter APB_ADDR_WIDTH = 12;
	input wire CLK;
	input wire RSTN;
	input wire [APB_ADDR_WIDTH - 1:0] PADDR;
	input wire [31:0] PWDATA;
	input wire PWRITE;
	input wire PSEL;
	input wire PENABLE;
	output reg [31:0] PRDATA;
	output wire PREADY;
	output wire PSLVERR;
	input wire rx_i;
	output wire tx_o;
	output wire event_o;
	parameter RBR = 3'h0;
	parameter THR = 3'h0;
	parameter DLL = 3'h0;
	parameter IER = 3'h1;
	parameter DLM = 3'h1;
	parameter IIR = 3'h2;
	parameter FCR = 3'h2;
	parameter LCR = 3'h3;
	parameter MCR = 3'h4;
	parameter LSR = 3'h5;
	parameter MSR = 3'h6;
	parameter SCR = 3'h7;
	parameter TX_FIFO_DEPTH = 16;
	parameter RX_FIFO_DEPTH = 16;
	wire [2:0] register_adr;
	reg [79:0] regs_q;
	reg [79:0] regs_n;
	reg [1:0] trigger_level_n;
	reg [1:0] trigger_level_q;
	wire [7:0] rx_data;
	wire parity_error;
	wire [3:0] IIR_o;
	reg [3:0] clr_int;
	wire tx_ready;
	reg apb_rx_ready;
	wire rx_valid;
	reg tx_fifo_clr_n;
	reg tx_fifo_clr_q;
	reg rx_fifo_clr_n;
	reg rx_fifo_clr_q;
	reg fifo_tx_valid;
	wire tx_valid;
	wire fifo_rx_valid;
	reg fifo_rx_ready;
	wire rx_ready;
	reg [7:0] fifo_tx_data;
	wire [8:0] fifo_rx_data;
	wire [7:0] tx_data;
	wire [$clog2(TX_FIFO_DEPTH):0] tx_elements;
	wire [$clog2(RX_FIFO_DEPTH):0] rx_elements;
	uart_rx uart_rx_i(
		.clk_i(CLK),
		.rstn_i(RSTN),
		.rx_i(rx_i),
		.cfg_en_i(1'b1),
		.cfg_div_i({regs_q[(DLM + 'd8) * 8+:8], regs_q[(DLL + 'd8) * 8+:8]}),
		.cfg_parity_en_i(regs_q[(LCR * 8) + 3]),
		.cfg_bits_i(regs_q[(LCR * 8) + 1-:2]),
		.busy_o(),
		.err_o(parity_error),
		.err_clr_i(1'b1),
		.rx_data_o(rx_data),
		.rx_valid_o(rx_valid),
		.rx_ready_i(rx_ready)
	);
	uart_tx uart_tx_i(
		.clk_i(CLK),
		.rstn_i(RSTN),
		.tx_o(tx_o),
		.busy_o(),
		.cfg_en_i(1'b1),
		.cfg_div_i({regs_q[(DLM + 'd8) * 8+:8], regs_q[(DLL + 'd8) * 8+:8]}),
		.cfg_parity_en_i(regs_q[(LCR * 8) + 3]),
		.cfg_bits_i(regs_q[(LCR * 8) + 1-:2]),
		.cfg_stop_bits_i(regs_q[(LCR * 8) + 2]),
		.tx_data_i(tx_data),
		.tx_valid_i(tx_valid),
		.tx_ready_o(tx_ready)
	);
	io_generic_fifo #(
		.DATA_WIDTH(9),
		.BUFFER_DEPTH(RX_FIFO_DEPTH)
	) uart_rx_fifo_i(
		.clk_i(CLK),
		.rstn_i(RSTN),
		.clr_i(rx_fifo_clr_q),
		.elements_o(rx_elements),
		.data_o(fifo_rx_data),
		.valid_o(fifo_rx_valid),
		.ready_i(fifo_rx_ready),
		.valid_i(rx_valid),
		.data_i({parity_error, rx_data}),
		.ready_o(rx_ready)
	);
	io_generic_fifo #(
		.DATA_WIDTH(8),
		.BUFFER_DEPTH(TX_FIFO_DEPTH)
	) uart_tx_fifo_i(
		.clk_i(CLK),
		.rstn_i(RSTN),
		.clr_i(tx_fifo_clr_q),
		.elements_o(tx_elements),
		.data_o(tx_data),
		.valid_o(tx_valid),
		.ready_i(tx_ready),
		.valid_i(fifo_tx_valid),
		.data_i(fifo_tx_data),
		.ready_o()
	);
	uart_interrupt #(
		.TX_FIFO_DEPTH(TX_FIFO_DEPTH),
		.RX_FIFO_DEPTH(RX_FIFO_DEPTH)
	) uart_interrupt_i(
		.clk_i(CLK),
		.rstn_i(RSTN),
		.IER_i(regs_q[(IER * 8) + 2-:3]),
		.RDA_i(regs_n[(LSR * 8) + 5]),
		.CTI_i(1'b0),
		.error_i(regs_n[(LSR * 8) + 2]),
		.rx_elements_i(rx_elements),
		.tx_elements_i(tx_elements),
		.trigger_level_i(trigger_level_q),
		.clr_int_i(clr_int),
		.interrupt_o(event_o),
		.IIR_o(IIR_o)
	);
	always @(*) begin
		if (_sv2v_0)
			;
		regs_n = regs_q;
		trigger_level_n = trigger_level_q;
		fifo_tx_valid = 1'b0;
		tx_fifo_clr_n = 1'b0;
		rx_fifo_clr_n = 1'b0;
		regs_n[LSR * 8] = fifo_rx_valid;
		regs_n[(LSR * 8) + 2] = fifo_rx_data[8];
		regs_n[(LSR * 8) + 5] = ~(|tx_elements);
		regs_n[(LSR * 8) + 6] = tx_ready & ~(|tx_elements);
		if ((PSEL && PENABLE) && PWRITE)
			case (register_adr)
				THR:
					if (regs_q[(LCR * 8) + 7])
						regs_n[(DLL + 'd8) * 8+:8] = PWDATA[7:0];
					else begin
						fifo_tx_data = PWDATA[7:0];
						fifo_tx_valid = 1'b1;
					end
				IER:
					if (regs_q[(LCR * 8) + 7])
						regs_n[(DLM + 'd8) * 8+:8] = PWDATA[7:0];
					else
						regs_n[IER * 8+:8] = PWDATA[7:0];
				LCR: regs_n[LCR * 8+:8] = PWDATA[7:0];
				FCR: begin
					rx_fifo_clr_n = PWDATA[1];
					tx_fifo_clr_n = PWDATA[2];
					trigger_level_n = PWDATA[7:6];
				end
				default:
					;
			endcase
	end
	always @(*) begin
		if (_sv2v_0)
			;
		PRDATA = 'b0;
		apb_rx_ready = 1'b0;
		fifo_rx_ready = 1'b0;
		clr_int = 4'b0000;
		if ((PSEL && PENABLE) && !PWRITE)
			case (register_adr)
				RBR:
					if (regs_q[(LCR * 8) + 7])
						PRDATA = {24'b000000000000000000000000, regs_q[(DLL + 'd8) * 8+:8]};
					else begin
						fifo_rx_ready = 1'b1;
						PRDATA = {24'b000000000000000000000000, fifo_rx_data[7:0]};
						clr_int = 4'b1000;
					end
				LSR: begin
					PRDATA = {24'b000000000000000000000000, regs_q[LSR * 8+:8]};
					clr_int = 4'b1100;
				end
				LCR: PRDATA = {24'b000000000000000000000000, regs_q[LCR * 8+:8]};
				IER:
					if (regs_q[(LCR * 8) + 7])
						PRDATA = {24'b000000000000000000000000, regs_q[(DLM + 'd8) * 8+:8]};
					else
						PRDATA = {24'b000000000000000000000000, regs_q[IER * 8+:8]};
				IIR: begin
					PRDATA = {28'b0000000000000000000000001100, IIR_o};
					clr_int = 4'b0100;
				end
				default:
					;
			endcase
	end
	always @(posedge CLK or negedge RSTN)
		if (~RSTN) begin
			regs_q[IER * 8+:8] <= 8'h00;
			regs_q[IIR * 8+:8] <= 8'h01;
			regs_q[LCR * 8+:8] <= 8'h00;
			regs_q[MCR * 8+:8] <= 8'h00;
			regs_q[LSR * 8+:8] <= 8'h60;
			regs_q[MSR * 8+:8] <= 8'h00;
			regs_q[SCR * 8+:8] <= 8'h00;
			regs_q[(DLM + 'd8) * 8+:8] <= 8'h00;
			regs_q[(DLL + 'd8) * 8+:8] <= 8'h00;
			trigger_level_q <= 2'b00;
			tx_fifo_clr_q <= 1'b0;
			rx_fifo_clr_q <= 1'b0;
		end
		else begin
			regs_q <= regs_n;
			trigger_level_q <= trigger_level_n;
			tx_fifo_clr_q <= tx_fifo_clr_n;
			rx_fifo_clr_q <= rx_fifo_clr_n;
		end
	assign register_adr = {PADDR[2:0]};
	assign PREADY = 1'b1;
	assign PSLVERR = 1'b0;
	initial _sv2v_0 = 0;
endmodule
module uart_rx (
	clk_i,
	rstn_i,
	rx_i,
	cfg_div_i,
	cfg_en_i,
	cfg_parity_en_i,
	cfg_bits_i,
	busy_o,
	err_o,
	err_clr_i,
	rx_data_o,
	rx_valid_o,
	rx_ready_i
);
	reg _sv2v_0;
	input wire clk_i;
	input wire rstn_i;
	input wire rx_i;
	input wire [15:0] cfg_div_i;
	input wire cfg_en_i;
	input wire cfg_parity_en_i;
	input wire [1:0] cfg_bits_i;
	output wire busy_o;
	output reg err_o;
	input wire err_clr_i;
	output wire [7:0] rx_data_o;
	output reg rx_valid_o;
	input wire rx_ready_i;
	reg [2:0] CS;
	reg [2:0] NS;
	reg [7:0] reg_data;
	reg [7:0] reg_data_next;
	reg [2:0] reg_rx_sync;
	reg [2:0] reg_bit_count;
	reg [2:0] reg_bit_count_next;
	reg [2:0] s_target_bits;
	reg parity_bit;
	reg parity_bit_next;
	reg sampleData;
	reg [15:0] baud_cnt;
	reg baudgen_en;
	reg bit_done;
	reg start_bit;
	reg set_error;
	wire s_rx_fall;
	assign busy_o = CS != 3'd0;
	always @(*) begin
		if (_sv2v_0)
			;
		case (cfg_bits_i)
			2'b00: s_target_bits = 3'h4;
			2'b01: s_target_bits = 3'h5;
			2'b10: s_target_bits = 3'h6;
			2'b11: s_target_bits = 3'h7;
		endcase
	end
	always @(*) begin
		if (_sv2v_0)
			;
		NS = CS;
		sampleData = 1'b0;
		reg_bit_count_next = reg_bit_count;
		reg_data_next = reg_data;
		rx_valid_o = 1'b0;
		baudgen_en = 1'b0;
		start_bit = 1'b0;
		parity_bit_next = parity_bit;
		set_error = 1'b0;
		case (CS)
			3'd0:
				if (s_rx_fall) begin
					NS = 3'd1;
					baudgen_en = 1'b1;
					start_bit = 1'b1;
				end
			3'd1: begin
				parity_bit_next = 1'b0;
				baudgen_en = 1'b1;
				start_bit = 1'b1;
				if (bit_done)
					NS = 3'd2;
			end
			3'd2: begin
				baudgen_en = 1'b1;
				parity_bit_next = parity_bit ^ reg_rx_sync[2];
				case (cfg_bits_i)
					2'b00: reg_data_next = {3'b000, reg_rx_sync[2], reg_data[4:1]};
					2'b01: reg_data_next = {2'b00, reg_rx_sync[2], reg_data[5:1]};
					2'b10: reg_data_next = {1'b0, reg_rx_sync[2], reg_data[6:1]};
					2'b11: reg_data_next = {reg_rx_sync[2], reg_data[7:1]};
				endcase
				if (bit_done) begin
					sampleData = 1'b1;
					if (reg_bit_count == s_target_bits) begin
						reg_bit_count_next = 'h0;
						NS = 3'd3;
					end
					else
						reg_bit_count_next = reg_bit_count + 1;
				end
			end
			3'd3: begin
				baudgen_en = 1'b1;
				rx_valid_o = 1'b1;
				if (rx_ready_i) begin
					if (cfg_parity_en_i)
						NS = 3'd4;
					else
						NS = 3'd5;
				end
			end
			3'd4: begin
				baudgen_en = 1'b1;
				if (bit_done) begin
					if (parity_bit != reg_rx_sync[2])
						set_error = 1'b1;
					NS = 3'd5;
				end
			end
			3'd5: begin
				baudgen_en = 1'b1;
				if (bit_done)
					NS = 3'd0;
			end
			default: NS = 3'd0;
		endcase
	end
	always @(posedge clk_i or negedge rstn_i)
		if (rstn_i == 1'b0) begin
			CS <= 3'd0;
			reg_data <= 8'hff;
			reg_bit_count <= 'h0;
			parity_bit <= 1'b0;
		end
		else begin
			if (bit_done)
				parity_bit <= parity_bit_next;
			if (sampleData)
				reg_data <= reg_data_next;
			reg_bit_count <= reg_bit_count_next;
			if (cfg_en_i)
				CS <= NS;
			else
				CS <= 3'd0;
		end
	assign s_rx_fall = ~reg_rx_sync[1] & reg_rx_sync[2];
	always @(posedge clk_i or negedge rstn_i)
		if (rstn_i == 1'b0)
			reg_rx_sync <= 3'b111;
		else if (cfg_en_i)
			reg_rx_sync <= {reg_rx_sync[1:0], rx_i};
		else
			reg_rx_sync <= 3'b111;
	always @(posedge clk_i or negedge rstn_i)
		if (rstn_i == 1'b0) begin
			baud_cnt <= 'h0;
			bit_done <= 1'b0;
		end
		else if (baudgen_en) begin
			if (!start_bit && (baud_cnt == cfg_div_i)) begin
				baud_cnt <= 'h0;
				bit_done <= 1'b1;
			end
			else if (start_bit && (baud_cnt == {1'b0, cfg_div_i[15:1]})) begin
				baud_cnt <= 'h0;
				bit_done <= 1'b1;
			end
			else begin
				baud_cnt <= baud_cnt + 1;
				bit_done <= 1'b0;
			end
		end
		else begin
			baud_cnt <= 'h0;
			bit_done <= 1'b0;
		end
	always @(posedge clk_i or negedge rstn_i)
		if (rstn_i == 1'b0)
			err_o <= 1'b0;
		else if (err_clr_i)
			err_o <= 1'b0;
		else if (set_error)
			err_o <= 1'b1;
	assign rx_data_o = reg_data;
	initial _sv2v_0 = 0;
endmodule
module uart_tx (
	clk_i,
	rstn_i,
	tx_o,
	busy_o,
	cfg_en_i,
	cfg_div_i,
	cfg_parity_en_i,
	cfg_bits_i,
	cfg_stop_bits_i,
	tx_data_i,
	tx_valid_i,
	tx_ready_o
);
	reg _sv2v_0;
	input wire clk_i;
	input wire rstn_i;
	output reg tx_o;
	output wire busy_o;
	input wire cfg_en_i;
	input wire [15:0] cfg_div_i;
	input wire cfg_parity_en_i;
	input wire [1:0] cfg_bits_i;
	input wire cfg_stop_bits_i;
	input wire [7:0] tx_data_i;
	input wire tx_valid_i;
	output reg tx_ready_o;
	reg [2:0] CS;
	reg [2:0] NS;
	reg [7:0] reg_data;
	reg [7:0] reg_data_next;
	reg [2:0] reg_bit_count;
	reg [2:0] reg_bit_count_next;
	reg [2:0] s_target_bits;
	reg parity_bit;
	reg parity_bit_next;
	reg sampleData;
	reg [15:0] baud_cnt;
	reg baudgen_en;
	reg bit_done;
	assign busy_o = CS != 3'd0;
	always @(*) begin
		if (_sv2v_0)
			;
		case (cfg_bits_i)
			2'b00: s_target_bits = 3'h4;
			2'b01: s_target_bits = 3'h5;
			2'b10: s_target_bits = 3'h6;
			2'b11: s_target_bits = 3'h7;
		endcase
	end
	always @(*) begin
		if (_sv2v_0)
			;
		NS = CS;
		tx_o = 1'b1;
		sampleData = 1'b0;
		reg_bit_count_next = reg_bit_count;
		reg_data_next = {1'b1, reg_data[7:1]};
		tx_ready_o = 1'b0;
		baudgen_en = 1'b0;
		parity_bit_next = parity_bit;
		case (CS)
			3'd0: begin
				if (cfg_en_i)
					tx_ready_o = 1'b1;
				if (tx_valid_i) begin
					NS = 3'd1;
					sampleData = 1'b1;
					reg_data_next = tx_data_i;
				end
			end
			3'd1: begin
				tx_o = 1'b0;
				parity_bit_next = 1'b0;
				baudgen_en = 1'b1;
				if (bit_done)
					NS = 3'd2;
			end
			3'd2: begin
				tx_o = reg_data[0];
				baudgen_en = 1'b1;
				parity_bit_next = parity_bit ^ reg_data[0];
				if (bit_done) begin
					if (reg_bit_count == s_target_bits) begin
						reg_bit_count_next = 'h0;
						if (cfg_parity_en_i)
							NS = 3'd3;
						else
							NS = 3'd4;
					end
					else begin
						reg_bit_count_next = reg_bit_count + 1;
						sampleData = 1'b1;
					end
				end
			end
			3'd3: begin
				tx_o = parity_bit;
				baudgen_en = 1'b1;
				if (bit_done)
					NS = 3'd4;
			end
			3'd4: begin
				tx_o = 1'b1;
				baudgen_en = 1'b1;
				if (bit_done) begin
					if (cfg_stop_bits_i)
						NS = 3'd5;
					else
						NS = 3'd0;
				end
			end
			3'd5: begin
				tx_o = 1'b1;
				baudgen_en = 1'b1;
				if (bit_done)
					NS = 3'd0;
			end
			default: NS = 3'd0;
		endcase
	end
	always @(posedge clk_i or negedge rstn_i)
		if (rstn_i == 1'b0) begin
			CS <= 3'd0;
			reg_data <= 8'hff;
			reg_bit_count <= 'h0;
			parity_bit <= 1'b0;
		end
		else begin
			if (bit_done)
				parity_bit <= parity_bit_next;
			if (sampleData)
				reg_data <= reg_data_next;
			reg_bit_count <= reg_bit_count_next;
			if (cfg_en_i)
				CS <= NS;
			else
				CS <= 3'd0;
		end
	always @(posedge clk_i or negedge rstn_i)
		if (rstn_i == 1'b0) begin
			baud_cnt <= 'h0;
			bit_done <= 1'b0;
		end
		else if (baudgen_en) begin
			if (baud_cnt == cfg_div_i) begin
				baud_cnt <= 'h0;
				bit_done <= 1'b1;
			end
			else begin
				baud_cnt <= baud_cnt + 1;
				bit_done <= 1'b0;
			end
		end
		else begin
			baud_cnt <= 'h0;
			bit_done <= 1'b0;
		end
	initial _sv2v_0 = 0;
endmodule
module io_generic_fifo (
	clk_i,
	rstn_i,
	clr_i,
	elements_o,
	data_o,
	valid_o,
	ready_i,
	valid_i,
	data_i,
	ready_o
);
	parameter DATA_WIDTH = 32;
	parameter BUFFER_DEPTH = 2;
	parameter LOG_BUFFER_DEPTH = $clog2(BUFFER_DEPTH);
	input wire clk_i;
	input wire rstn_i;
	input wire clr_i;
	output wire [LOG_BUFFER_DEPTH:0] elements_o;
	output wire [DATA_WIDTH - 1:0] data_o;
	output wire valid_o;
	input wire ready_i;
	input wire valid_i;
	input wire [DATA_WIDTH - 1:0] data_i;
	output wire ready_o;
	reg [LOG_BUFFER_DEPTH - 1:0] pointer_in;
	reg [LOG_BUFFER_DEPTH - 1:0] pointer_out;
	reg [LOG_BUFFER_DEPTH:0] elements;
	reg [DATA_WIDTH - 1:0] buffer [BUFFER_DEPTH - 1:0];
	wire full;
	reg [31:0] loop1;
	assign full = elements == BUFFER_DEPTH;
	assign elements_o = elements;
	always @(posedge clk_i or negedge rstn_i) begin : elements_sequential
		if (rstn_i == 1'b0)
			elements <= 0;
		else if (clr_i)
			elements <= 0;
		else if ((ready_i && valid_o) && (!valid_i || full))
			elements <= elements - 1;
		else if (((!valid_o || !ready_i) && valid_i) && !full)
			elements <= elements + 1;
	end
	always @(posedge clk_i or negedge rstn_i) begin : buffers_sequential
		if (rstn_i == 1'b0)
			for (loop1 = 0; loop1 < BUFFER_DEPTH; loop1 = loop1 + 1)
				buffer[loop1] <= 0;
		else if (valid_i && !full)
			buffer[pointer_in] <= data_i;
	end
	always @(posedge clk_i or negedge rstn_i) begin : sequential
		if (rstn_i == 1'b0) begin
			pointer_out <= 0;
			pointer_in <= 0;
		end
		else if (clr_i) begin
			pointer_out <= 0;
			pointer_in <= 0;
		end
		else begin
			if (valid_i && !full) begin
				if (pointer_in == $unsigned(BUFFER_DEPTH - 1))
					pointer_in <= 0;
				else
					pointer_in <= pointer_in + 1;
			end
			if (ready_i && valid_o) begin
				if (pointer_out == $unsigned(BUFFER_DEPTH - 1))
					pointer_out <= 0;
				else
					pointer_out <= pointer_out + 1;
			end
		end
	end
	assign data_o = buffer[pointer_out];
	assign valid_o = elements != 0;
	assign ready_o = ~full;
endmodule
module uart_interrupt (
	clk_i,
	rstn_i,
	IER_i,
	RDA_i,
	CTI_i,
	error_i,
	rx_elements_i,
	tx_elements_i,
	trigger_level_i,
	clr_int_i,
	interrupt_o,
	IIR_o
);
	reg _sv2v_0;
	parameter TX_FIFO_DEPTH = 32;
	parameter RX_FIFO_DEPTH = 32;
	input wire clk_i;
	input wire rstn_i;
	input wire [2:0] IER_i;
	input wire RDA_i;
	input wire CTI_i;
	input wire error_i;
	input wire [$clog2(RX_FIFO_DEPTH):0] rx_elements_i;
	input wire [$clog2(TX_FIFO_DEPTH):0] tx_elements_i;
	input wire [1:0] trigger_level_i;
	input wire [3:0] clr_int_i;
	output wire interrupt_o;
	output wire [3:0] IIR_o;
	reg [3:0] iir_n;
	reg [3:0] iir_q;
	reg trigger_level_reached;
	always @(*) begin
		if (_sv2v_0)
			;
		trigger_level_reached = 1'b0;
		case (trigger_level_i)
			2'b00:
				if ($unsigned(rx_elements_i) == 1)
					trigger_level_reached = 1'b1;
			2'b01:
				if ($unsigned(rx_elements_i) == 4)
					trigger_level_reached = 1'b1;
			2'b10:
				if ($unsigned(rx_elements_i) == 8)
					trigger_level_reached = 1'b1;
			2'b11:
				if ($unsigned(rx_elements_i) == 14)
					trigger_level_reached = 1'b1;
			default:
				;
		endcase
	end
	always @(*) begin
		if (_sv2v_0)
			;
		if (clr_int_i == 4'b0000)
			iir_n = iir_q;
		else
			iir_n = iir_q & ~clr_int_i;
		if (IER_i[2] & error_i)
			iir_n = 4'b1100;
		else if (IER_i[0] & (trigger_level_reached | RDA_i))
			iir_n = 4'b1000;
		else if (IER_i[0] & CTI_i)
			iir_n = 4'b1000;
		else if (IER_i[1] & (tx_elements_i == 0))
			iir_n = 4'b0100;
	end
	always @(posedge clk_i or negedge rstn_i)
		if (~rstn_i)
			iir_q <= 4'b0001;
		else
			iir_q <= iir_n;
	assign IIR_o = iir_q;
	assign interrupt_o = ~iir_q[0];
	initial _sv2v_0 = 0;
endmodule
