"""
The environment: one APB agent, a scoreboard that models the loopback, and the
register model generated from regs/apb_uart.rdl.

The scoreboard never looks at the serial line. `tx_o` is tied back to `rx_i`, so
every byte written to THR has to reappear, in order, from RBR -- and that is the
whole design in one relation: APB decode, TX FIFO, serialiser, deserialiser, RX
FIFO. Modelling the bit timing here would assert the DUT's divisor arithmetic
against a second copy of the same arithmetic, which proves nothing and breaks
whenever the divisor changes.

It follows the register writes to know what the data reads mean: at offset 0x0 a
write is THR and a read is RBR, but only while LCR[7] is clear -- with DLAB set
the same address is the divisor latch and has nothing to do with the FIFOs.
"""

from collections import deque

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, Edge
from pyuvm import (ConfigDB, set_sv_uvm_style_reporting_enabled,
                   uvm_endianness_e, uvm_env, uvm_subscriber, uvm_test)

from apb_agent import DLAB, FCR, LCR, RBR, THR, ApbAgent, ApbRegAdapter
from uart_ral import apb_uart

# Nanoseconds, and `make rtl` puts a `timescale in the generated Verilog so that
# they mean the same thing on the RTL and on the gates. cocotb's "step" unit does
# not: a gate-level run compiles the PDK cell models alongside the netlist, those
# carry 1ns/1ps, and a step there is a picosecond -- while the RTL on its own has
# no timescale at all, so a step is a second. The same two-step clock was 2 ps of
# gates and 2 s of RTL, which is how `make gatesim` first failed.
CLOCK_PERIOD_NS = 10


class LoopbackScoreboard(uvm_subscriber):
    """Every byte sent must come back, in order, and nothing may be left over."""

    def build_phase(self):
        self.expected = deque()
        self.matched = 0
        self.failures = []
        self.dlab = False

    def write(self, txn):
        if txn.write and txn.addr == LCR:
            self.dlab = bool(txn.data & DLAB)
            return

        # FIFO clears are the one thing that legitimately loses data in flight.
        if txn.write and txn.addr == FCR and txn.data & 0b110:
            self.expected.clear()
            return

        if self.dlab:
            return          # divisor latches, not data

        if txn.write and txn.addr == THR:
            self.expected.append(txn.data & 0xFF)
        elif not txn.write and txn.addr == RBR:
            got = txn.rdata & 0xFF
            if not self.expected:
                self.failures.append(f"read 0x{got:02x} from RBR with nothing sent")
            else:
                want = self.expected.popleft()
                if got != want:
                    self.failures.append(f"sent 0x{want:02x}, RBR returned 0x{got:02x}")
                else:
                    self.matched += 1

    def check_phase(self):
        if self.expected:
            left = ", ".join(f"0x{b:02x}" for b in self.expected)
            self.failures.append(f"never came back out of RBR: {left}")
        if self.failures:
            raise AssertionError("; ".join(self.failures))


class UartEnv(uvm_env):
    def build_phase(self):
        self.agent = ApbAgent("agent", self)
        self.scoreboard = LoopbackScoreboard("scoreboard", self)
        # Generated by `make ral` from regs/apb_uart.rdl. build() is the model's,
        # not a UVM phase: it constructs the map and adds the registers to it.
        # lock_model() is what resolves the addresses -- without it every access
        # dies on "unsupported operand type(s) for +: 'NoneType' and 'int'", after
        # a warning that the map "does not seem to initialized correctly".
        self.regs = apb_uart("regs")
        self.regs.build()

        # PeakRDL-pyuvm creates the map with UVM_NO_ENDIAN, and pyuvm's
        # uvm_reg_map reads that as "no endianness specified": it takes the error
        # branch in _get_physical_addresses_to_map, leaves the address list unset,
        # and every access then dies on "unsupported operand type(s) for +:
        # 'NoneType' and 'int'". So the map is reconfigured with one before the
        # model is locked. Which one cannot matter here -- the registers are eight
        # bits on a byte-addressed map, so no register spans two addresses for an
        # order to apply to -- but pyuvm insists on being told.
        self.regs.get_default_map().configure(
            self.regs, 0, 1, uvm_endianness_e.UVM_LITTLE_ENDIAN)

        # The mirror follows the accesses the register layer performs, and only
        # those. UVM's other option is a uvm_reg_predictor on the monitor, which
        # predicts from observed bus traffic and is the better setup in general --
        # it catches writes the register layer did not initiate. It is the wrong
        # one here: the monitor also sees the THR, FCR and divisor-latch traffic
        # that regs/apb_uart.rdl deliberately does not describe, and a predictor
        # would feed an FCR write at 0x2 into IIR's mirror, because that is the
        # register the map has at that address.
        #
        # Without either, the mirror stays at its reset value and a written
        # register reads back as a mismatch: "Register 'regs.LCR' value read from
        # DUT (0x5F) does not match mirrored value (0x0)".
        self.regs.get_default_map().set_auto_predict(True)

        # lock_model() resolves the addresses. Without it every access fails the
        # same way, after a warning that the map "does not seem to initialized
        # correctly".
        self.regs.lock_model()

    def connect_phase(self):
        self.agent.ap.connect(self.scoreboard.analysis_export)
        self.regs.get_default_map().set_sequencer(self.agent.sequencer,
                                                 ApbRegAdapter("reg_adapter"))


async def bring_up(dut):
    """Clock, reset, and the loopback that makes the DUT talk to itself."""
    cocotb.start_soon(Clock(dut.CLK, CLOCK_PERIOD_NS, units="ns").start())

    dut.RSTN.value = 0
    dut.PSEL.value = 0
    dut.PENABLE.value = 0
    dut.PWRITE.value = 0
    dut.PADDR.value = 0
    dut.PWDATA.value = 0
    dut.rx_i.value = 1          # an idle line is high; 0 would look like a start bit
    await ClockCycles(dut.CLK, 4)
    dut.RSTN.value = 1
    await ClockCycles(dut.CLK, 4)

    # Driven off tx_o changing rather than off the clock. A clocked mirror reads
    # the pre-edge value and so adds a cycle of latency to the serial line, which
    # the RTL tolerates and the netlist -- compiled with -DUNIT_DELAY, so every
    # cell costs a step -- might not. A wire has no latency; this is a wire.
    async def tie_tx_to_rx():
        dut.rx_i.value = dut.tx_o.value
        while True:
            await Edge(dut.tx_o)
            dut.rx_i.value = dut.tx_o.value
    cocotb.start_soon(tie_tx_to_rx())


class UartTest(uvm_test):
    """Builds the environment and checks the scoreboard saw exactly what was sent.

    `payload` is what the test puts through the loopback -- empty for a test that
    only touches registers. Checking the count rather than "more than none" is
    what makes the register tests able to share this base class without the
    scoreboard having to guess whether silence was expected.
    """

    payload = ()

    def build_phase(self):
        # Here, not in bring_up: uvm_root().run_test() clears the singletons
        # before it builds the tree, so anything put in the ConfigDB beforehand
        # is gone by the time the agent looks for it. uvm_test_top's build_phase
        # runs before its children's, which is early enough.
        ConfigDB().set(None, "*", "dut", cocotb.top)

        # Without this the register layer's errors go to a plain logging logger
        # named "RegModel" and the report server never counts them -- so
        # mirror(UVM_CHECK) would log a mismatch and the test would still pass.
        # Measured: with an IER write redirected to MCR in the RTL, that is
        # exactly what happened. With it, RAL errors go through uvm_report and
        # test_ral.py can ask how many there were.
        set_sv_uvm_style_reporting_enabled(True)

        self.env = UartEnv("env", self)

    async def run_phase(self):
        self.raise_objection()
        await self.run()
        self.drop_objection()

    async def run(self):
        raise NotImplementedError("a UartTest has to do something")

    def check_phase(self):
        got = self.env.scoreboard.matched
        want = len(self.payload)
        if got != want:
            raise AssertionError(
                f"the scoreboard matched {got} bytes through the loopback, not {want}"
            )
