
# This file was autogenerated by PeakRDL-pyuvm
from typing import TypeVar, Callable

import numpy as np
from numpy.typing import NDArray

from pyuvm import (
    uvm_coverage_model_e,
    uvm_endianness_e,
    uvm_mem,
    uvm_reg,
    uvm_reg_block,
    uvm_reg_field,
)

T = TypeVar('T')


def create_object_array(factory: Callable[[], T], name: str, dimensions: list[int]) -> NDArray[T]:
    """
    Creates a multidimensional NumPy array with the given `dimensions`, where each element
    is created by calling `factory`.

    Parameters:
        dimensions (list[int]): The size of each dimension in the resulting array.
        factory (Callable[[], T]): A no-argument callable (like a class or function)
                                   that returns an instance of T.

    Returns:
        NDArray[T]: A NumPy array populated with instances created by factory().
    """
    arr = np.empty(dimensions, dtype=object)
    for idx in np.ndindex(*dimensions):
        indicies = ''.join(f'[{i}]' for i in idx)
        arr[idx] = factory(f"{name}{indicies}")
    return arr


# Reg - apb_uart::IER
class apb_uart__IER(uvm_reg):

    def __init__(self, name: str = "IER"):
        super().__init__(name, 8, uvm_coverage_model_e.UVM_NO_COVERAGE)
        self.RDA = uvm_reg_field("RDA")
        self.THRE = uvm_reg_field("THRE")
        self.RLS = uvm_reg_field("RLS")

    def build(self) -> None:
        self.RDA.configure(self, 1, 0, "RW", False, 0x0, True, True, False)
        self.THRE.configure(self, 1, 1, "RW", False, 0x0, True, True, False)
        self.RLS.configure(self, 1, 2, "RW", False, 0x0, True, True, False)


# Reg - apb_uart::IIR
class apb_uart__IIR(uvm_reg):

    def __init__(self, name: str = "IIR"):
        super().__init__(name, 8, uvm_coverage_model_e.UVM_NO_COVERAGE)
        self.INT_ID = uvm_reg_field("INT_ID")
        self.RSVD = uvm_reg_field("RSVD")
        self.FIFO_EN = uvm_reg_field("FIFO_EN")

    def build(self) -> None:
        self.INT_ID.configure(self, 4, 0, "RO", True, 0x1, True, True, False)
        self.RSVD.configure(self, 2, 4, "RO", False, 0x0, True, True, False)
        self.FIFO_EN.configure(self, 2, 6, "RO", False, 0x3, True, True, False)


# Reg - apb_uart::LCR
class apb_uart__LCR(uvm_reg):

    def __init__(self, name: str = "LCR"):
        super().__init__(name, 8, uvm_coverage_model_e.UVM_NO_COVERAGE)
        self.WLS = uvm_reg_field("WLS")
        self.STB = uvm_reg_field("STB")
        self.PEN = uvm_reg_field("PEN")
        self.EPS = uvm_reg_field("EPS")
        self.SP = uvm_reg_field("SP")
        self.BC = uvm_reg_field("BC")
        self.DLAB = uvm_reg_field("DLAB")

    def build(self) -> None:
        self.WLS.configure(self, 2, 0, "RW", False, 0x0, True, True, False)
        self.STB.configure(self, 1, 2, "RW", False, 0x0, True, True, False)
        self.PEN.configure(self, 1, 3, "RW", False, 0x0, True, True, False)
        self.EPS.configure(self, 1, 4, "RW", False, 0x0, True, True, False)
        self.SP.configure(self, 1, 5, "RW", False, 0x0, True, True, False)
        self.BC.configure(self, 1, 6, "RW", False, 0x0, True, True, False)
        self.DLAB.configure(self, 1, 7, "RW", False, 0x0, True, True, False)


# Reg - apb_uart::LSR
class apb_uart__LSR(uvm_reg):

    def __init__(self, name: str = "LSR"):
        super().__init__(name, 8, uvm_coverage_model_e.UVM_NO_COVERAGE)
        self.DR = uvm_reg_field("DR")
        self.OE = uvm_reg_field("OE")
        self.PE = uvm_reg_field("PE")
        self.FE = uvm_reg_field("FE")
        self.BI = uvm_reg_field("BI")
        self.THRE = uvm_reg_field("THRE")
        self.TEMT = uvm_reg_field("TEMT")
        self.FIFOERR = uvm_reg_field("FIFOERR")

    def build(self) -> None:
        self.DR.configure(self, 1, 0, "RO", True, 0x0, True, True, False)
        self.OE.configure(self, 1, 1, "RO", False, 0x0, True, True, False)
        self.PE.configure(self, 1, 2, "RO", True, 0x0, True, True, False)
        self.FE.configure(self, 1, 3, "RO", False, 0x0, True, True, False)
        self.BI.configure(self, 1, 4, "RO", False, 0x0, True, True, False)
        self.THRE.configure(self, 1, 5, "RO", True, 0x1, True, True, False)
        self.TEMT.configure(self, 1, 6, "RO", True, 0x1, True, True, False)
        self.FIFOERR.configure(self, 1, 7, "RO", False, 0x0, True, True, False)


# Addrmap - apb_uart
class apb_uart(uvm_reg_block):

    def __init__(self, name: str = "apb_uart"):
        super().__init__(name)
        self.IER = apb_uart__IER("IER")
        self.IIR = apb_uart__IIR("IIR")
        self.LCR = apb_uart__LCR("LCR")
        self.LSR = apb_uart__LSR("LSR")

    def build(self) -> None:
        reg_map = self.create_map("reg_map", 0, 1, uvm_endianness_e.UVM_NO_ENDIAN)
        self.set_default_map(reg_map)
        self.IER = apb_uart__IER("IER")
        self.IER.configure(self, None, "")

        self.IER.build()
        self.get_default_map().add_reg(self.IER, 0x1, "RW")
        self.IIR = apb_uart__IIR("IIR")
        self.IIR.configure(self, None, "")

        self.IIR.build()
        self.get_default_map().add_reg(self.IIR, 0x2, "RO")
        self.LCR = apb_uart__LCR("LCR")
        self.LCR.configure(self, None, "")

        self.LCR.build()
        self.get_default_map().add_reg(self.LCR, 0x3, "RW")
        self.LSR = apb_uart__LSR("LSR")
        self.LSR.configure(self, None, "")

        self.LSR.build()
        self.get_default_map().add_reg(self.LSR, 0x5, "RO")
